# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Texture'
  pod 'Alamofire'
  pod 'DifferenceKit'
  pod 'RXCDiffArray', :path=> '../../RXCDiffArray'
  pod 'RXCDiffArray/DifferenceKit', :path=> '../../RXCDiffArray'
  pod 'RXCDiffArray/ASDKExtension', :path=> '../../RXCDiffArray'

  pod 'RXCSwiftComponents', :path=> '../../RXCSwiftComponents'
  pod 'RXCSwiftComponents/Texture', :path=> '../../RXCSwiftComponents'
  pod 'RXCSwiftComponents/MJRefresh', :path=> '../../RXCSwiftComponents'
  pod 'RXCSwiftComponents/Alamofire', :path=> '../../RXCSwiftComponents'

  pod 'RXCLoadingStateManager', :path=> '../../RXCLoadingStateManager'

  pod 'RXCFirstTimeViewController', :path=> '../../RXCFirstTimeViewController'

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
