# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RXCEntityListViewController', :path=> '../'
  pod 'RXCEntityListViewController/Texture', :path=> '../'

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
