# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RXCEntityListViewController' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'Texture', '~> 2.8'
    pod 'RXCDiffArray', :path => "/Users/ruixingchen/Developer/Mine/RXCDiffArray"
    pod 'RXCDiffArray/ASDKExtension', :path => "/Users/ruixingchen/Developer/Mine/RXCDiffArray"
    pod 'RXCDiffArray/DifferenceKit', :path => "/Users/ruixingchen/Developer/Mine/RXCDiffArray"
#    pod 'RXCDiffArray', :git => "https://github.com/ruixingchen/RXCDiffArray.git"

end
